name: Bazel Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup-and-run-tests:
    runs-on: ${{ vars.REPO_RUNNER_LABELS && fromJSON(vars.REPO_RUNNER_LABELS) || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install protoc 26.1
        uses: arduino/setup-protoc@v3
        with:
          version: 26.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bazel with shared caching
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: 1.26.0
          disk-cache: true
          repository-cache: true
          bazelisk-cache: true

      - name: Run Tests via Bazel
        run: |
          echo "Running: bazel test //src/..."
          bazel test //src/...
